services:
  backend:
    build:
      context: ./xmt-Backend
    container_name: xmt-backend
    ports:
      - "8080:8080"
    # tại vì dùng xampp nên phải khai báo file này, còn nếu có thêm 1 thằng db nữa thì tính tiếp
    env_file:
      - ./xmt-Backend/.env
    # chú ý cái con khỉ khô này
    volumes:
      - ./xmt-Backend:/app
      - /app/node_modules
    networks:
      - ximusic-network
    restart: unless-stopped

  frontend:
    build:
      context: ./xmt-Frontend
    container_name: xms-frontend
    ports:
      - "5173:5173"
      # chú ý cái con khỉ khô này
    volumes:
      - ./xmt-Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - ximusic-network
    restart: unless-stopped

networks:
  ximusic-network:
    driver: bridge
