name: XiMusic CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  Frontend:
    runs-on: ubuntu-latest

    steps:
      # lấy src từ repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # setup node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # như cái tên
      - name: Install Frontend dependencies
        # làm việc tại folder đó (cd)
        working-directory: ./xmt-Frontend
        # dùng CI vì nếu đã có node thì nó xóa rồi cài lại luôn, tiện hơn ins
        run: npm ci

      # Au tu tét
      - name: Lint Frontend
        working-directory: ./xmt-Frontend
        # check ở trong thằng script của quoắc king đia
        run: npm run lint

      - name: Build Backend
        working-directory: ./xmt-Backend
        run: npm run build

  Backend:
    runs-on: ubuntu-latest
    steps:
      # lấy src từ repo
      - name: Checkout source code
        uses: actions/checkout@v4

      # setup node
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      # như cái tên
      - name: Install Backend dependencies
        # làm việc tại folder đó (cd)
        working-directory: ./xmt-Backend
        # dùng CI vì nếu đã có node thì nó xóa rồi cài lại luôn, tiện hơn ins
        run: npm ci

         # như cái tên
      - name: Build Frontend
        working-directory: ./xmt-Frontend
        run: npm run build



