name: XiMusic CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:

  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Frontend dependencies
        working-directory: ./xmt-Frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./xmt-Frontend
        run: npm run lint

      - name: Build Frontend
        working-directory: ./xmt-Frontend
        run: npm run build

  backend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install Backend dependencies
        working-directory: ./xmt-Backend
        run: npm ci

      - name: Build Backend
        working-directory: ./xmt-Backend
        run: npm run build





