name: Docker CD

on:
  push:
    branches:
      - Learn_CI/CD

jobs:
  docker:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./xmt-Backend
        # dấu | là bắt thực hiện trình tự theo hàng
        run: |
          docker build \
            -t ghcr.io/lnnhuttuong/xms-backend:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/lnnhuttuong/xms-backend:latest
