name: Docker CD

on:
  push:
    branches:
      - learn-CI/CD

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build docker image
        working-directory: ./xmt-Backend
        run: |
          docker build \
          -t ghcr.io/lnnhuttuong/xms-backend:latest \
          .

      - name: push docker image
        run: |
          docker push ghcr.io/lnnhuttuong/xms-backend:latest
