name: Deploy

on:
  push:
    branches:
      - Learn_CI/CD

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy to fake VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/github_actions_cd
          chmod 600 ~/.ssh/github_actions_cd

          ssh -i ~/.ssh/github_actions_cd \
          -p 2222 \
          -o StrictHostKeyChecking=no \
          deploy@localhost \
          "echo '$GHCR_TOKEN' | docker login ghcr.io -u '$GHCR_USERNAME' --password-stdin &&
          docker stop xms-backend || true &&
          docker rm xms-backend || true &&
          docker pull ghcr.io/lnnhuttuong/xms-backend:latest &&
          docker run -d \
            --name xms-backend \
            -p 8081:8081 \
            -e PORT=8081 \
            -e DB_HOST=172.17.0.1 \
            -e DB_PORT=3306 \
            -e DB_USER=root \
            -e DB_PASSWORD=123456 \
            -e DB_NAME=ximusic \
            -e JWT_SECRET=athulaso1 \
            -e JWT_EXPIRES_IN=1d \
            ghcr.io/lnnhuttuong/xms-backend:latest"



