name: Test Self Hosted Runner

on:
  push:
    branches:
      - master

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Test runner
        run: |
          echo "Hello from self-hosted runner"
          whoami
          hostname
          docker --version
